### ISSUE TITLE
Sort does not work.

### ISSUE THREAD

**Issue by pantsonfire** [NSFWUTILS/RedditScrape#13]
How can I add sorting by top and number in the config? Seems the new version does not allow it.

**Comment by NSFWUTILS** [comment]
You're right, the new versions are based on pulling everything through push shift so we don't have to use the reddit API at all. This allows for a much greater set of files, but loses the ability to sort...You could go back to trying my [original release](https://github.com/NSFWUTILS/RedditScrape/releases/tag/v1.0.0) to see if it works for you, but at this point I just don't have the time to support both options.
