### ISSUE TITLE
max number of works / shows completed even tho there should be more works. | failed to find libmagic. (installed via pip)

### ISSUE THREAD

**Issue by ShiroUwUs7** [NSFWUTILS/RedditScrape#15]
> The JSON text alone is currently 9 gigs and climbing. 

Is there a setting that you changed to achive this? Mine is only at around 380mbs, even apon re running it, it says its complete is there a max amount of works that it can grab or did I not set up something correctly? 

![GM1JMmt 1](https://user-images.githubusercontent.com/53096166/236725920-707f737f-7de8-4e6b-b323-93f9c6406226.png)

Also unable to start the download process due to libmagic not being found even tho it is installed: 
![OFpUTIj 1](https://user-images.githubusercontent.com/53096166/236726374-354847d0-02fd-4022-8af1-15ced3f1514a.png)

**Comment by NSFWUTILS** [comment]
l should have this fixed in the latest release. If you still run into issues, you can just make sure to remove the line `import magic` from `utils.py` (should be one of the first lines in the file).
