### ISSUE TITLE
Failed to find libmagic

### ISSUE THREAD

**Issue by Wasd-klmp** [NSFWUTILS/RedditScrape#9]
Ran the code with libmagic installed on Windows 10 but cant seem to make it work for some reason

`  File "C:\Users\USER\Desktop\RedditScrape-main\utils.py", line 2, in <module>
    import magic
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\magic\__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\magic\loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
`

**Comment by NSFWUTILS** [comment]
Thanks, I keep thinking I've fixed this and apparently I keep failing. 

I no longer need this, so the easiest way would be to comment out line 2 from utils.py (change it to this: `# import magic`). I'm working on a substantial rework (yet again...this shit is hard) which should have the fix in place, and a lot of other improvements.

**Comment by NSFWUTILS** [comment]
New version has been uploaded, please let me know if you still have an issue.

**Comment by destro225** [comment]
Was fixed for me by installing python-magic-bin. 
`pip install python-magic-bin`
